travis:
  secure:
    BINSTAR_TOKEN: w04jbOVESbSSbzsPcxu/3ID+51k7a0ycCleAcWFt/3LpJTRsvtQOvgAGm4Wf7z3aj8MxHPv/HXtqAv2JorNdx/DmTB9EX7PBE7QDf0CP7N0Br+Ls6IS3JlAHmHJF6CBJPvZyfkpJZCHNuu3Cj2q3HRx4do+IS+HtH+GmXhayzSOAEaUD2m7jU/ZWalkg9u0BS0zBxqLNrzApjzre7wcG6fsGLHp0pYoQ1+5aceD680qAP1YQDS4kf0hE9ZuNuncDXMtN1N/nxBUmFIJ2ZZ7yfgH6BOkKknnBQE13QedyNKonK4WXKm+EOYI/krddIskt1CR5TY+kWkFpZdYVq76fUSI7GXR8/oHSfht2IGATUpBjJrGJVKkOw7O4ai6yzMAWAxtHT0eKGorHvxnBJ9kkXk2fyXiLZNA2zXQFC4tTzztAWKWwugNH0522szuKK52TbRCHjZ9Om8pLBC1UErmTLO8O+vk/SJdvoHZDBz91Nn47cUChU4hHGmBICnm1d5eTr+NwO8F3/lgfjbWVdb1rrxA/KfNXoAi4PsqA4JY8XiEhSZ6rAYAj8VPlQWUjGOBh6mbmErd1hnnZxkpq8GhMgUKR8Cy7viZWtpjXy+P+izSgYYhfIB+LBFF8IEbma7nSz0KLQmgIJmrcDlAgLVCkFCEVNnrWBjhhS+idDeCuSxk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
